config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :products
  resources :products

  root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to products_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :quantity, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "AmazonRailsApp" %></title>
	<%= csrf_meta_tags %>

	<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

      <%= javascript_include_tag "application" %>
  </head>
  <body>

  	<div class="navbar navbar-default navbar-static-top">
  		<div class="container">
  			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
  				<span class="icon-bar"></span>
  				<span class="icon-bar"></span>
  				<span class="icon-bar"></span>
  			</button>
  			<a class="navbar-brand" href="#">AmazonRailsApp</a>
  			<div class="navbar-collapse collapse navbar-responsive-collapse">
  				<ul class="nav navbar-nav navbar-right">
  					<% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
  					<% else %>
  					<li><%= link_to "Register", "/users/sign_up"  %></li>
  					<li><%= link_to "Login", "/users/sign_in"  %></li>

  					<% end %>
  				</ul>
  			</div>
  		</div>
  	</div>

  	<div class="container">
  		<div class="row">
  			<div class="col-lg-12">
  				<%= bootstrap_flash %>
  				<%= yield %>
  			</div>
  		</div><!--/row-->

  		<footer>
  			<!-- <p>&copy; Company 2015</p> -->
  		</footer>

  	</div> <!-- /container -->

  </body>
  </html>

app/views/products/_form.html.erb
<div class="card card-container">
  <h1>New Product</h1>
  <%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name,:placeholder => "Name", :class => "form-control" %> 
  </div>
  <div class="field">
    <%= f.text_area :description,:placeholder => "Description",:class => "form-control" %>
  </div>
  <div class="field">
    <%= f.text_field :price,:placeholder => "Price", :class => "form-control"%>
  </div>
  <div class="field">
    <%= f.text_field :quantity,:placeholder => "Quantity",:class => "form-control" %>
  </div>
  <div class="field">
    <%= f.file_field :image,:placeholder => "Image" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  <%= link_to  new_product_path do %><button class="btn btn-default">New Product</button><%end%>
  <h1>Listing Products</h1>
  <table class="table">
    <thead>
      <tr class="success">
        <th>NAME</th>
        <th>DESCRIPTION</th>
        <th>PRICE</th>
        <th>QUANTITY</th>
        <th>IMAGE</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
      <tr class="success">
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= link_to 'SHOW', product %></td>
        <td><%= link_to 'EDIT', edit_product_path(product) %></td>
        <td><%= link_to 'DESTROY' , product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<table class="table table-stribe">
  <thead>
    <tr class="success">
      <th><strong>Name:</strong></th>
      <th><strong>Description:</strong></th>
      <th><strong>Price:</strong></th>
      <th><strong>Quantity:</strong></th>
      <th><strong>Image:</strong></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <tr class="success">
      <td><%= @product.name %></td>
      <td><%= @product.description %></td>
      <td><%= @product.price %></td>
      <td><%= @product.quantity %></td>
      <td><%=image_tag @product.image.url(:thumb) %></td>
      <td>
        <%= link_to 'Edit', edit_product_path(@product) %> |
        <%= link_to 'Back', products_path %>
      </td>
    </tr>
  </tbody>
</table>